// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    [Migration("20230903164529_TIN_Updated_CHK")]
    partial class TIN_Updated_CHK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryId = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CountryName = "Australia"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.Property<string>("TIN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(8)")
                        .HasDefaultValue("ABC12345")
                        .HasColumnName("TaxIdentificationNumber");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasCheckConstraint("CHK_TIN", "len([TaxIdentificationNumber]) = 8");

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("410673c8-1c16-4df2-9bcb-cd4afdf6a118"),
                            Address = "1234 Elm St.",
                            CountryId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            Gender = "Male",
                            PersonName = "John Doe",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("3bfbc420-3617-42e4-a643-774abeb44077"),
                            Address = "5678 Oak St.",
                            CountryId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            DateOfBirth = new DateTime(1990, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            Gender = "Female",
                            PersonName = "Jane Smith",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("3422507a-54fc-4b1a-8903-d08dc386b8ae"),
                            Address = "9 Maple Ave.",
                            CountryId = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            DateOfBirth = new DateTime(1995, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.johnson@example.com",
                            Gender = "Male",
                            PersonName = "Michael Johnson",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("5252d13b-71a7-4b7f-93be-deef5e3cc81d"),
                            Address = "101 Pine Drive",
                            CountryId = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            DateOfBirth = new DateTime(1988, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.davis@example.com",
                            Gender = "Female",
                            PersonName = "Emily Davis",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("624c11fd-03ed-4869-93e4-46fa0b111277"),
                            Address = "202 Birch Lane",
                            CountryId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            DateOfBirth = new DateTime(1975, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "william.brown@example.com",
                            Gender = "Male",
                            PersonName = "William Brown",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("1a1d43c0-72ec-41f4-95f1-0e61eab3c58c"),
                            Address = "303 Cedar Place",
                            CountryId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            DateOfBirth = new DateTime(1992, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jessica.taylor@example.com",
                            Gender = "Female",
                            PersonName = "Jessica Taylor",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("ce90ea9d-873b-4ef6-aea5-ba3e5ed1f423"),
                            Address = "404 Elmwood Drive",
                            CountryId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            DateOfBirth = new DateTime(1989, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert.lee@example.com",
                            Gender = "Male",
                            PersonName = "Robert Lee",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("c8cfe443-9dae-4ff8-90ce-0d2a10cc20f5"),
                            Address = "505 Fir St.",
                            CountryId = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            DateOfBirth = new DateTime(1978, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "angela.white@example.com",
                            Gender = "Female",
                            PersonName = "Angela White",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("1c08a9ac-c8f6-487c-a0d6-ccde4e583eb5"),
                            Address = "606 Grove Avenue",
                            CountryId = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            DateOfBirth = new DateTime(1999, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.wilson@example.com",
                            Gender = "Male",
                            PersonName = "James Wilson",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("4d051dee-565a-462a-be87-7a6875f08348"),
                            Address = "707 Hickory Blvd.",
                            CountryId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            DateOfBirth = new DateTime(1993, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophia.moore@example.com",
                            Gender = "Female",
                            PersonName = "Sophia Moore",
                            ReceiveNewsLetters = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
