// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(PersonsDbContext))]
    [Migration("20230903073959_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<Guid>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries", (string)null);

                    b.HasData(
                        new
                        {
                            CountryId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            CountryName = "Philippines"
                        },
                        new
                        {
                            CountryId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            CountryName = "India"
                        },
                        new
                        {
                            CountryId = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            CountryName = "USA"
                        },
                        new
                        {
                            CountryId = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            CountryName = "Canada"
                        },
                        new
                        {
                            CountryId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            CountryName = "Australia"
                        });
                });

            modelBuilder.Entity("Entities.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ReceiveNewsLetters")
                        .HasColumnType("bit");

                    b.HasKey("PersonId");

                    b.ToTable("Persons", (string)null);

                    b.HasData(
                        new
                        {
                            PersonId = new Guid("341c4097-b6b7-405f-af0a-38a7d1f0c37b"),
                            Address = "1234 Elm St.",
                            CountryId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            DateOfBirth = new DateTime(1985, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            Gender = "Male",
                            PersonName = "John Doe",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("7994552c-d3f5-4737-a91c-4c6579dfc178"),
                            Address = "5678 Oak St.",
                            CountryId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            DateOfBirth = new DateTime(1990, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.smith@example.com",
                            Gender = "Female",
                            PersonName = "Jane Smith",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("fd5eb70c-832d-48f7-a4f8-7e8cd5b9f065"),
                            Address = "9 Maple Ave.",
                            CountryId = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            DateOfBirth = new DateTime(1995, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.johnson@example.com",
                            Gender = "Male",
                            PersonName = "Michael Johnson",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("ca26e084-248a-4d58-a153-4fffd7274ce6"),
                            Address = "101 Pine Drive",
                            CountryId = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            DateOfBirth = new DateTime(1988, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "emily.davis@example.com",
                            Gender = "Female",
                            PersonName = "Emily Davis",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("235c8254-0c06-4589-8d08-a11d1c546dd2"),
                            Address = "202 Birch Lane",
                            CountryId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            DateOfBirth = new DateTime(1975, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "william.brown@example.com",
                            Gender = "Male",
                            PersonName = "William Brown",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("dae94dc9-b3e6-40be-b50e-6abff205370f"),
                            Address = "303 Cedar Place",
                            CountryId = new Guid("a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1"),
                            DateOfBirth = new DateTime(1992, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jessica.taylor@example.com",
                            Gender = "Female",
                            PersonName = "Jessica Taylor",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("f6d75019-7492-4704-9b47-7a90e3889e68"),
                            Address = "404 Elmwood Drive",
                            CountryId = new Guid("b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2"),
                            DateOfBirth = new DateTime(1989, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "robert.lee@example.com",
                            Gender = "Male",
                            PersonName = "Robert Lee",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("5a42e97a-6aac-487d-9222-efe17eced8a1"),
                            Address = "505 Fir St.",
                            CountryId = new Guid("c3c3c3c3-c3c3-c3c3-c3c3-c3c3c3c3c3c3"),
                            DateOfBirth = new DateTime(1978, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "angela.white@example.com",
                            Gender = "Female",
                            PersonName = "Angela White",
                            ReceiveNewsLetters = true
                        },
                        new
                        {
                            PersonId = new Guid("5ab4851c-2b5a-43fa-8dc2-953a1a28a5ec"),
                            Address = "606 Grove Avenue",
                            CountryId = new Guid("d4d4d4d4-d4d4-d4d4-d4d4-d4d4d4d4d4d4"),
                            DateOfBirth = new DateTime(1999, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "james.wilson@example.com",
                            Gender = "Male",
                            PersonName = "James Wilson",
                            ReceiveNewsLetters = false
                        },
                        new
                        {
                            PersonId = new Guid("08118bb1-d221-46c4-8e9c-996344acec13"),
                            Address = "707 Hickory Blvd.",
                            CountryId = new Guid("e5e5e5e5-e5e5-e5e5-e5e5-e5e5e5e5e5e5"),
                            DateOfBirth = new DateTime(1993, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophia.moore@example.com",
                            Gender = "Female",
                            PersonName = "Sophia Moore",
                            ReceiveNewsLetters = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
